language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DKU7r6/GnvHkhxVV8HLaHhvk8bwaOF6pRNKE8HOkshQxd8d3+hIgEAMAFb4IiN/xsL31bE62H8EbY2697FnijQRef8N5k7r+bNLRLNndkwjQ99newzbe/+/NYdpVNwbQfQ/vqBU4jU7iGFw87NSKCwYdou9LejvRENaY6U8eC9PrAF043QwRRHDDjihXwMQF8ewgPfr594RK9H3E11S2squyK6PZ13A3MG65e7FleuUKoIYIsgAOz04XGqcBb081B6FxozbpRAqGD+Jvuddiry9WQCAoEv1RWog09ZZpnlxMqs+pjPp+7vgSmQ7maI0k+kICKFkzShoXmw2T/FYLSJgxcEfssPMf79p3YYv2viB7HAW4Ixl6APktiJrym0DmiYmS7c10g6EpltyFx5NnVCG7PJs556eUJlA/s7wPVjIs3vrl4jyT/1uugmbf0P5OX4IUq0CJQRhVBzZs78SQcpVTQXtGSLI/a/TKoROUhRqhJ/iApaNrWCD9vuWOprAWRKMKpEX8ZLi/etSmn5drLuEp8ByCEikMN6P9ZQuX/82Oi11FcZUbr8ZB+p4cm4uP+b14EYuI+lK5IMO4gc8JNnYIFo0Iqhw3M5CXgoveKRau0SZzRKL1A3Ghua/AS/YRbjEVrQJF5hMzrlW4z7p+U0JrUgjY0ZjBwtkS2VtMUDw=
  app: fierce-journey-96916
  on:
    repo: steviebuckets/on-wax
